// ─── AI Report Card Component ───────────────────────────────────────────────
// Comprehensive, production-grade visual report generated by the JanSamadhan
// AI Engine. Shared by both Citizen submission flow and Government portal.

import React from 'react';
import {
  Sparkles,
  ShieldCheck,
  AlertTriangle,
  FileQuestion,
  Copy,
  CheckCircle2,
  TrendingUp,
  Tag,
  GraduationCap,
  Layers,
  ArrowRight,
  Info,
  Clock,
  ExternalLink,
} from 'lucide-react';
import type { AIReport } from '../../types/aiReportTypes';

interface AIReportCardProps {
  report: AIReport;
  mode?: 'full' | 'compact';
  onTrackStatus?: () => void;
  onViewMyProblems?: () => void;
  onViewSimilarProblem?: (problemId: string) => void;
}

export const AIReportCard: React.FC<AIReportCardProps> = ({
  report,
  mode = 'full',
  onTrackStatus,
  onViewMyProblems,
  onViewSimilarProblem,
}) => {
  const {
    summary,
    classification,
    verification,
    completeness,
    priority,
    duplicateDetection,
    aiExplanation,
    recommendedAction,
    analyzedAt,
    disclaimer,
  } = report;

  // Verification status styling helper
  const getVerificationBadge = () => {
    switch (verification.status) {
      case 'ASSESSED':
        return {
          label: 'AI Assessed',
          subtext: 'Meets initial automated criteria',
          bg: 'bg-emerald-50 dark:bg-emerald-950/40',
          border: 'border-emerald-200 dark:border-emerald-800',
          text: 'text-emerald-700 dark:text-emerald-300',
          icon: ShieldCheck,
        };
      case 'NEEDS_REVIEW':
        return {
          label: 'Requires Officer Review',
          subtext: 'Flagged for detailed manual assessment',
          bg: 'bg-amber-50 dark:bg-amber-950/40',
          border: 'border-amber-200 dark:border-amber-800',
          text: 'text-amber-700 dark:text-amber-300',
          icon: AlertTriangle,
        };
      case 'POSSIBLE_DUPLICATE':
        return {
          label: 'Possible Duplicate Detected',
          subtext: 'Matches existing civic grievance',
          bg: 'bg-purple-50 dark:bg-purple-950/40',
          border: 'border-purple-200 dark:border-purple-800',
          text: 'text-purple-700 dark:text-purple-300',
          icon: Copy,
        };
      case 'INSUFFICIENT_INFORMATION':
      default:
        return {
          label: 'More Information Needed',
          subtext: 'Critical details missing for expedited triage',
          bg: 'bg-rose-50 dark:bg-rose-950/40',
          border: 'border-rose-200 dark:border-rose-800',
          text: 'text-rose-700 dark:text-rose-300',
          icon: FileQuestion,
        };
    }
  };

  const getPriorityBadge = () => {
    switch (priority.level) {
      case 'CRITICAL':
        return {
          bg: 'bg-red-500/10 text-red-700 dark:text-red-400 border-red-200 dark:border-red-900',
          barBg: 'bg-red-500',
        };
      case 'HIGH':
        return {
          bg: 'bg-orange-500/10 text-orange-700 dark:text-orange-400 border-orange-200 dark:border-orange-900',
          barBg: 'bg-orange-500',
        };
      case 'MEDIUM':
        return {
          bg: 'bg-blue-500/10 text-blue-700 dark:text-blue-400 border-blue-200 dark:border-blue-900',
          barBg: 'bg-blue-500',
        };
      case 'LOW':
      default:
        return {
          bg: 'bg-slate-500/10 text-slate-700 dark:text-slate-400 border-slate-200 dark:border-slate-800',
          barBg: 'bg-slate-500',
        };
    }
  };

  const verBadge = getVerificationBadge();
  const VerIcon = verBadge.icon;
  const priBadge = getPriorityBadge();

  return (
    <div className="w-full space-y-6 animate-fade-in text-slate-800 dark:text-slate-100">
      {/* ── Header Banner ─────────────────────────────────────────────────── */}
      <div className="rounded-2xl border border-indigo-200 dark:border-indigo-900/60 bg-gradient-to-r from-indigo-50/70 via-white to-cyan-50/50 dark:from-slate-900 dark:via-slate-900 dark:to-indigo-950/40 p-5 sm:p-6 shadow-sm">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-indigo-600 to-cyan-500 flex items-center justify-center text-white shadow-md">
              <Sparkles className="w-6 h-6" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <span className="text-xs font-semibold uppercase tracking-wider text-indigo-600 dark:text-indigo-400">
                  Automated AI Analysis
                </span>
                <span className="inline-flex items-center px-2 py-0.5 rounded text-[10px] font-mono bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300">
                  {report.id}
                </span>
              </div>
              <h3 className="text-lg sm:text-xl font-bold text-slate-900 dark:text-white">
                Intelligent Civic Verification Report
              </h3>
            </div>
          </div>

          <div className="flex items-center gap-2 text-xs text-slate-500 dark:text-slate-400 self-start sm:self-auto">
            <Clock className="w-3.5 h-3.5" />
            <span>Analyzed {new Date(analyzedAt).toLocaleString()}</span>
          </div>
        </div>

        {/* Verification Status Highlight Bar */}
        <div className={`mt-4 p-4 rounded-xl border ${verBadge.bg} ${verBadge.border} flex items-start gap-3`}>
          <VerIcon className={`w-5 h-5 flex-shrink-0 mt-0.5 ${verBadge.text}`} />
          <div className="flex-1 min-w-0">
            <div className="flex flex-wrap items-center gap-2">
              <span className={`font-semibold text-sm ${verBadge.text}`}>
                {verBadge.label}
              </span>
              <span className="text-xs bg-white/80 dark:bg-slate-900/80 px-2 py-0.5 rounded-full font-medium text-slate-600 dark:text-slate-300 border border-current/20">
                Confidence: {verification.confidence}%
              </span>
            </div>
            <p className="text-xs sm:text-sm mt-1 text-slate-600 dark:text-slate-300 leading-relaxed">
              {verification.explanation}
            </p>
          </div>
        </div>
      </div>

      {/* ── Key Metrics Grid (Priority, Completeness, Duplicate) ─────────────── */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        {/* Metric 1: Priority */}
        <div className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-4 shadow-sm">
          <div className="flex items-center justify-between mb-2">
            <span className="text-xs font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400">
              Priority Assessment
            </span>
            <span
              className={`text-xs font-bold px-2 py-0.5 rounded-full border ${priBadge.bg}`}
            >
              {priority.level}
            </span>
          </div>
          <div className="flex items-baseline gap-2 mb-2">
            <span className="text-3xl font-black text-slate-900 dark:text-white">
              {priority.score}
            </span>
            <span className="text-xs text-slate-500 font-medium">/ 100</span>
          </div>
          <div className="w-full h-2 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden mb-2">
            <div
              className={`h-full rounded-full ${priBadge.barBg}`}
              style={{ width: `${priority.score}%` }}
            />
          </div>
          <p className="text-xs text-slate-600 dark:text-slate-400 line-clamp-2">
            {priority.reason}
          </p>
        </div>

        {/* Metric 2: Submission Completeness */}
        <div className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-4 shadow-sm">
          <div className="flex items-center justify-between mb-2">
            <span className="text-xs font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400">
              Completeness Score
            </span>
            <span className="text-xs font-semibold text-emerald-600 dark:text-emerald-400">
              {completeness.score >= 80 ? 'Well Documented' : completeness.score >= 50 ? 'Adequate' : 'Sparse'}
            </span>
          </div>
          <div className="flex items-baseline gap-2 mb-2">
            <span className="text-3xl font-black text-slate-900 dark:text-white">
              {completeness.score}%
            </span>
            <span className="text-xs text-slate-500 font-medium">of required details</span>
          </div>
          <div className="w-full h-2 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden mb-2">
            <div
              className={`h-full rounded-full ${
                completeness.score >= 80
                  ? 'bg-emerald-500'
                  : completeness.score >= 50
                  ? 'bg-amber-500'
                  : 'bg-rose-500'
              }`}
              style={{ width: `${completeness.score}%` }}
            />
          </div>
          <p className="text-xs text-slate-600 dark:text-slate-400">
            {completeness.providedFields.length} data fields captured & verified
          </p>
        </div>

        {/* Metric 3: Duplicate Status */}
        <div className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-4 shadow-sm">
          <div className="flex items-center justify-between mb-2">
            <span className="text-xs font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400">
              Duplicate Detection
            </span>
            <span
              className={`text-xs font-bold px-2 py-0.5 rounded-full border ${
                duplicateDetection.status === 'UNIQUE'
                  ? 'bg-emerald-50 text-emerald-700 border-emerald-200 dark:bg-emerald-950/40 dark:text-emerald-300 dark:border-emerald-800'
                  : 'bg-amber-50 text-amber-700 border-amber-200 dark:bg-amber-950/40 dark:text-amber-300 dark:border-amber-800'
              }`}
            >
              {duplicateDetection.status.replace('_', ' ')}
            </span>
          </div>
          <div className="flex items-baseline gap-2 mb-2">
            <span className="text-3xl font-black text-slate-900 dark:text-white">
              {duplicateDetection.similarProblems.length === 0
                ? '0'
                : duplicateDetection.similarProblems.length}
            </span>
            <span className="text-xs text-slate-500 font-medium">similar issues found</span>
          </div>
          <p className="text-xs text-slate-600 dark:text-slate-400 line-clamp-3">
            {duplicateDetection.explanation}
          </p>
        </div>
      </div>

      {/* ── Problem Summary & Classification ─────────────────────────────────── */}
      <div className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-5 sm:p-6 shadow-sm space-y-5">
        <div>
          <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1.5 flex items-center gap-1.5">
            <Layers className="w-3.5 h-3.5 text-indigo-500" />
            AI Executive Summary
          </h4>
          <p className="text-sm sm:text-base font-medium text-slate-900 dark:text-slate-100 leading-relaxed bg-slate-50 dark:bg-slate-800/50 p-3.5 rounded-xl border border-slate-100 dark:border-slate-800">
            {summary}
          </p>
        </div>

        {/* Classification Details */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2 border-t border-slate-100 dark:border-slate-800">
          <div>
            <span className="text-xs font-semibold text-slate-500 dark:text-slate-400 block mb-1">
              Primary Domain & Subcategory
            </span>
            <div className="flex items-center gap-2">
              <span className="px-2.5 py-1 rounded-md bg-indigo-50 dark:bg-indigo-950/60 text-indigo-700 dark:text-indigo-300 font-semibold text-xs border border-indigo-200 dark:border-indigo-800">
                {classification.domainLabel}
              </span>
              <span className="text-xs text-slate-600 dark:text-slate-400">
                / {classification.subcategory}
              </span>
            </div>
          </div>

          <div>
            <span className="text-xs font-semibold text-slate-500 dark:text-slate-400 block mb-1">
              Extracted Keywords
            </span>
            <div className="flex flex-wrap gap-1.5">
              {classification.keywords.map((kw, i) => (
                <span
                  key={i}
                  className="inline-flex items-center gap-1 px-2 py-0.5 rounded bg-slate-100 dark:bg-slate-800 text-[11px] text-slate-700 dark:text-slate-300"
                >
                  <Tag className="w-2.5 h-2.5 text-slate-400" />
                  {kw}
                </span>
              ))}
            </div>
          </div>
        </div>

        {/* Suggested Department for Officials */}
        {classification.suggestedDepartment && (
          <div className="pt-2 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between gap-2">
            <span className="text-xs font-semibold text-slate-500 dark:text-slate-400">
              Suggested Department
            </span>
            <span className="text-xs font-bold text-cyan-800 dark:text-cyan-300 bg-cyan-50 dark:bg-cyan-950/40 px-2.5 py-1 rounded-lg border border-cyan-200 dark:border-cyan-800">
              {classification.suggestedDepartment}
            </span>
          </div>
        )}

        {/* Required Academic / R&D Expertise */}
        {classification.requiredExpertise.length > 0 && (
          <div className="pt-2 border-t border-slate-100 dark:border-slate-800">
            <span className="text-xs font-semibold text-slate-500 dark:text-slate-400 flex items-center gap-1.5 mb-2">
              <GraduationCap className="w-4 h-4 text-indigo-600 dark:text-indigo-400" />
              Recommended Academic / Technical Expertise
            </span>
            <div className="flex flex-wrap gap-2">
              {classification.requiredExpertise.map((exp, i) => (
                <span
                  key={i}
                  className="px-2.5 py-1 rounded-lg text-xs font-medium bg-cyan-50 dark:bg-cyan-950/30 text-cyan-800 dark:text-cyan-300 border border-cyan-200 dark:border-cyan-800"
                >
                  {exp}
                </span>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* ── Similar Problems (if any found) ─────────────────────────────────── */}
      {duplicateDetection.similarProblems.length > 0 && (
        <div className="rounded-2xl border border-amber-200 dark:border-amber-900/60 bg-amber-50/30 dark:bg-amber-950/20 p-5 shadow-sm">
          <div className="flex items-center gap-2 mb-3 text-amber-800 dark:text-amber-300 font-semibold text-sm">
            <Copy className="w-4 h-4" />
            <span>Potentially Related Grievances Detected in Region</span>
          </div>
          <div className="space-y-2">
            {duplicateDetection.similarProblems.map((sim) => (
              <div
                key={sim.id}
                className="flex items-center justify-between p-3 rounded-xl bg-white dark:bg-slate-900 border border-amber-200/60 dark:border-amber-900/40 text-xs"
              >
                <div className="min-w-0 flex-1 mr-3">
                  <div className="font-semibold text-slate-900 dark:text-white truncate">
                    {sim.title}
                  </div>
                  <div className="text-slate-500 flex items-center gap-2 mt-0.5">
                    <span>ID: {sim.id}</span>
                    <span>•</span>
                    <span className="capitalize">{sim.status}</span>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <span className="px-2 py-0.5 rounded font-mono font-bold bg-amber-100 dark:bg-amber-950 text-amber-700 dark:text-amber-300">
                    {sim.similarity}% Match
                  </span>
                  {onViewSimilarProblem && (
                    <button
                      type="button"
                      onClick={() => onViewSimilarProblem(sim.id)}
                      className="p-1 rounded text-slate-500 hover:text-indigo-600"
                    >
                      <ExternalLink className="w-3.5 h-3.5" />
                    </button>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ── Completeness Breakdown ─────────────────────────────────────────── */}
      <div className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-5 sm:p-6 shadow-sm">
        <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-3 flex items-center gap-1.5">
          <CheckCircle2 className="w-4 h-4 text-emerald-500" />
          Submission Quality Audit
        </h4>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <span className="text-xs font-medium text-slate-600 dark:text-slate-400 block mb-2">
              Captured & Validated Fields
            </span>
            <ul className="space-y-1.5">
              {completeness.providedFields.map((field, i) => (
                <li key={i} className="flex items-center gap-2 text-xs text-slate-700 dark:text-slate-300">
                  <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500 flex-shrink-0" />
                  <span>{field}</span>
                </li>
              ))}
            </ul>
          </div>

          <div>
            <span className="text-xs font-medium text-slate-600 dark:text-slate-400 block mb-2">
              {completeness.missingInformation.length > 0
                ? 'Information Recommended for Follow-Up'
                : 'All Essential Criteria Satisfied'}
            </span>
            {completeness.missingInformation.length > 0 ? (
              <ul className="space-y-1.5">
                {completeness.missingInformation.map((item, i) => (
                  <li key={i} className="flex items-center gap-2 text-xs text-amber-700 dark:text-amber-400">
                    <Info className="w-3.5 h-3.5 text-amber-500 flex-shrink-0" />
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-xs text-emerald-600 dark:text-emerald-400">
                All mandatory verification criteria have been adequately furnished.
              </p>
            )}
          </div>
        </div>
      </div>

      {/* ── AI Explanation & Recommended Action ─────────────────────────────── */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Explanation */}
        <div className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-5 shadow-sm">
          <div className="flex items-center gap-2 mb-2 text-indigo-700 dark:text-indigo-400 font-semibold text-xs uppercase tracking-wider">
            <TrendingUp className="w-4 h-4" />
            AI Decision Rationale
          </div>
          <p className="text-xs sm:text-sm text-slate-600 dark:text-slate-300 leading-relaxed">
            {aiExplanation}
          </p>
        </div>

        {/* Next Step */}
        <div className="rounded-2xl border border-indigo-200 dark:border-indigo-900/60 bg-gradient-to-br from-indigo-50/50 to-white dark:from-slate-900 dark:to-indigo-950/20 p-5 shadow-sm">
          <div className="flex items-center gap-2 mb-2 text-indigo-700 dark:text-indigo-400 font-semibold text-xs uppercase tracking-wider">
            <ArrowRight className="w-4 h-4" />
            Recommended Officer Action
          </div>
          <p className="text-xs sm:text-sm font-medium text-slate-800 dark:text-slate-200 leading-relaxed">
            {recommendedAction}
          </p>
        </div>
      </div>

      {/* ── Official AI Advisory Notice / Disclaimer ───────────────────────── */}
      <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-800/40 border border-slate-200 dark:border-slate-800 flex items-start gap-2.5 text-slate-500 dark:text-slate-400 text-xs">
        <Info className="w-4 h-4 flex-shrink-0 mt-0.5 text-slate-400" />
        <p className="leading-relaxed">
          {disclaimer}
        </p>
      </div>

      {/* ── Actions (Citizen Mode) ─────────────────────────────────────────── */}
      {mode === 'full' && (onTrackStatus || onViewMyProblems) && (
        <div className="flex flex-col sm:flex-row items-center justify-end gap-3 pt-4 border-t border-slate-200 dark:border-slate-800">
          {onViewMyProblems && (
            <button
              type="button"
              onClick={onViewMyProblems}
              className="w-full sm:w-auto px-5 py-2.5 rounded-xl border border-slate-300 dark:border-slate-700 text-slate-700 dark:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 font-semibold text-sm transition-colors shadow-sm"
            >
              Go to My Problems
            </button>
          )}
          {onTrackStatus && (
            <button
              type="button"
              onClick={onTrackStatus}
              className="w-full sm:w-auto px-6 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-semibold text-sm transition-colors shadow-md flex items-center justify-center gap-2"
            >
              <span>Track Problem Status</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          )}
        </div>
      )}
    </div>
  );
};
export default AIReportCard;
